In [2]:
!pip uninstall -y torch-geometric torch-scatter torch-sparse torch-cluster torch-spline-conv
!pip install torch-geometric

Found existing installation: torch-geometric 2.6.1
Uninstalling torch-geometric-2.6.1:
  Successfully uninstalled torch-geometric-2.6.1

WARNING: Skipping torch-scatter as it is not installed.
WARNING: Skipping torch-sparse as it is not installed.
WARNING: Skipping torch-cluster as it is not installed.
WARNING: Skipping torch-spline-conv as it is not installed.

Defaulting to user installation because normal site-packages is not writeable
Collecting torch-geometric
  Using cached torch_geometric-2.6.1-py3-none-any.whl.metadata (63 kB)
Requirement already satisfied: aiohttp in c:\programdata\anaconda3\lib\site-packages (from torch-geometric) (3.9.5)
Requirement already satisfied: fsspec in c:\programdata\anaconda3\lib\site-packages (from torch-geometric) (2024.3.1)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from torch-geometric) (3.1.4)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from torch-geometric) (1.26.4)
Requirement already satisfied: psutil>=5.8.0 in c:\programdata\anaconda3\lib\site-packages (from torch-geometric) (5.9.0)
Requirement already satisfied: pyparsing in c:\programdata\anaconda3\lib\site-packages (from torch-geometric) (3.0.9)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from torch-geometric) (2.32.2)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from torch-geometric) (4.66.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\programdata\anaconda3\lib\site-packages (from aiohttp->torch-geometric) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\programdata\anaconda3\lib\site-packages (from aiohttp->torch-geometric) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\programdata\anaconda3\lib\site-packages (from aiohttp->torch-geometric) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\programdata\anaconda3\lib\site-packages (from aiohttp->torch-geometric) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\programdata\anaconda3\lib\site-packages (from aiohttp->torch-geometric) (1.9.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->torch-geometric) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->torch-geometric) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->torch-geometric) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->torch-geometric) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->torch-geometric) (2024.7.4)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm->torch-geometric) (0.4.6)
Using cached torch_geometric-2.6.1-py3-none-any.whl (1.1 MB)
Installing collected packages: torch-geometric
Successfully installed torch-geometric-2.6.1

In [2]:
import numpy as np
import pandas as pd
import random
from torch_geometric.data import HeteroData
import torch

In [3]:
user_df = pd.read_csv('../../data/preproccedData/Augmented_PreProccedNutrationParameters.csv')
food_df = pd.read_csv('../../data/RecommandationDatasets/NutritionDatasets/Foods_Datasets.csv')
disease_df = pd.read_csv('../../data/RecommandationDatasets/NutritionDatasets/diseases.csv')
nutrition_df = pd.read_csv('../../data/RecommandationDatasets/NutritionDatasets/nutrients.csv')

In [4]:
user_df.head()

,Age,Gender,Height,Weight,Carbohydrate_Consumption,Protein_Intake,Fat_Intake,Regularity_of_Meals,Portion_Control,Hydration,Caloric_Balance,Sugar_Consumption,BMI,DiabetesRisk,NutritionRisk
0,24,1,160.39,53.08,2,1,1,1,1,2,2106.59,1,16.60,29.69,54.09
1,24,1,158.47,58.42,1,2,1,0,1,1,2106.58,1,18.71,31.04,36.07
2,28,0,146.93,50.97,3,3,1,0,2,2,2106.58,1,18.99,28.55,18.03
3,24,0,156.55,59.46,2,1,1,1,3,5,1378.17,2,19.52,36.28,36.04
4,22,0,147.91,48.84,2,1,1,1,2,3,2106.59,3,17.95,24.35,18.03

In [5]:
user_df["user_id"] = ["u" + str(i + 1) for i in range(len(user_df))]

# Randomly assign preferred culture
cultures = ["Sri Lankan", "Western", "Mixed"]
user_df["preferred_culture"] = [random.choice(cultures) for _ in range(len(user_df))]

# Save the required columns
users_gnn = user_df[["user_id", "preferred_culture"]]

In [6]:
user_df.head()

,Age,Gender,Height,Weight,Carbohydrate_Consumption,Protein_Intake,Fat_Intake,Regularity_of_Meals,Portion_Control,Hydration,Caloric_Balance,Sugar_Consumption,BMI,DiabetesRisk,NutritionRisk,user_id,preferred_culture
0,24,1,160.39,53.08,2,1,1,1,1,2,2106.59,1,16.60,29.69,54.09,u1,Sri Lankan
1,24,1,158.47,58.42,1,2,1,0,1,1,2106.58,1,18.71,31.04,36.07,u2,Western
2,28,0,146.93,50.97,3,3,1,0,2,2,2106.58,1,18.99,28.55,18.03,u3,Mixed
3,24,0,156.55,59.46,2,1,1,1,3,5,1378.17,2,19.52,36.28,36.04,u4,Western
4,22,0,147.91,48.84,2,1,1,1,2,3,2106.59,3,17.95,24.35,18.03,u5,Sri Lankan

In [7]:
user_df.to_csv("../../data/RecommandationDatasets/NutritionDatasets/Updated_User_Nutrition_Parameters.csv", index=False)

In [8]:
food_df.head()

,food_id,food_item,calories,carbs,protein,fat,glycemic_index,meal_type,culture,estimated_weight_g
0,f1000,Millet with fish and tomato,1140.535373,152.9,45.9,33.6,52,Breakfast,Sri Lankan,877
1,f1001,Rice with chicken and cabbage,750.478011,78.3,39.0,29.0,69,Breakfast,Sri Lankan,577
2,f1002,Millet with chicken and beans,1197.418738,149.6,52.2,40.9,52,Dinner,Sri Lankan,921
3,f1003,Millet with beef and onion,1271.988528,72.4,35.8,92.9,63,Lunch,Sri Lankan,978
4,f1004,Wheat with egg and cucumber,948.852773,120.8,37.1,32.2,69,Dinner,Sri Lankan,730

In [9]:
num_foods = len(food_df)
food_df['food_id'] = [f'f{i:04d}' for i in range(1, num_foods + 1)]
food_df['calories'] = food_df['calories'].round(1)

# Save the required columns
foods_gnn = food_df[['food_id', 'culture']]

# Display the updated DataFrame
food_df.head()

,food_id,food_item,calories,carbs,protein,fat,glycemic_index,meal_type,culture,estimated_weight_g
0,f0001,Millet with fish and tomato,1140.5,152.9,45.9,33.6,52,Breakfast,Sri Lankan,877
1,f0002,Rice with chicken and cabbage,750.5,78.3,39.0,29.0,69,Breakfast,Sri Lankan,577
2,f0003,Millet with chicken and beans,1197.4,149.6,52.2,40.9,52,Dinner,Sri Lankan,921
3,f0004,Millet with beef and onion,1272.0,72.4,35.8,92.9,63,Lunch,Sri Lankan,978
4,f0005,Wheat with egg and cucumber,948.9,120.8,37.1,32.2,69,Dinner,Sri Lankan,730

In [10]:


# 1. User hasRisk Diabetes (for demo, assume all users have diabetes risk)
user_risk_edges = user_df['user_id'].apply(lambda uid: [uid, 'hasRisk', 'd1']).tolist()

# 2. User prefers culture
user_pref_edges = user_df[['user_id', 'preferred_culture']].apply(lambda row: [row['user_id'], 'prefers', row['preferred_culture']], axis=1).tolist()

# 3. Food contains nutrient
nutrient_map = {'protein': 'n1', 'carbs': 'n2', 'fat': 'n3'}
food_nutrient_edges = []
for _, row in food_df.iterrows():
    fid = row['food_id']
    for col, nid in nutrient_map.items():
        if col in row and not pd.isna(row[col]) and float(row[col]) > 0:
            food_nutrient_edges.append([fid, 'contains', nid])

# 4. Food raises glycemic index category
def gi_category(gi):
    try:
        gi = float(gi)
        if gi < 55: return "Low_GI"
        elif gi <= 69: return "Medium_GI"
        else: return "High_GI"
    except:
        return None

food_gi_edges = []
for _, row in food_df.iterrows():
    category = gi_category(row['glycemic_index'])
    if category:
        food_gi_edges.append([row['food_id'], 'raises', category])

# Combine all edges
all_edges = user_risk_edges + user_pref_edges + food_nutrient_edges + food_gi_edges
edges_df = pd.DataFrame(all_edges, columns=['source', 'relation', 'target'])

# Save to CSV
edges_path = "../../data/RecommandationDatasets/NutritionDatasets/edges.csv"
edges_df.to_csv(edges_path, index=False)

edges_path

'../../data/RecommandationDatasets/NutritionDatasets/edges.csv'

In [11]:

from collections import defaultdict

# Load datasets
user_df = pd.read_csv("../../data/RecommandationDatasets/NutritionDatasets/Updated_User_Nutrition_Parameters.csv")
food_df = pd.read_csv("../../data/RecommandationDatasets/NutritionDatasets/Foods_Datasets.csv")
nutrition_df = pd.read_csv("../../data/RecommandationDatasets/NutritionDatasets/nutrients.csv")
disease_df = pd.read_csv("../../data/RecommandationDatasets/NutritionDatasets/diseases.csv")
edges = pd.read_csv("../../data/RecommandationDatasets/NutritionDatasets/edges.csv")

# Encode categorical columns
risk_map = {'Low': 0.0, 'Medium': 1.0, 'High': 2.0}
user_df['DiabetesRisk'] = user_df['DiabetesRisk'].map(risk_map)
user_df['NutritionRisk'] = user_df['NutritionRisk'].map(risk_map)

# Create HeteroData graph
data = HeteroData()

# Add user features
user_features = user_df[['Age', 'Gender', 'Height', 'Weight', 'Carbohydrate_Consumption',
                         'Protein_Intake', 'Fat_Intake', 'Regularity_of_Meals', 'Portion_Control',
                         'Caloric_Balance', 'Sugar_Consumption', 'BMI',
                         'DiabetesRisk', 'NutritionRisk']].astype(float)
data['user'].x = torch.tensor(user_features.values, dtype=torch.float)
user_id_map = {uid: i for i, uid in enumerate(user_df['user_id'])}

# Add food features (no food_id in feature set!)
food_features = food_df[['calories', 'carbs', 'protein', 'fat', 'glycemic_index', 'estimated_weight_g']].astype(float)
data['food'].x = torch.tensor(food_features.values, dtype=torch.float)
food_id_map = {fid: i for i, fid in enumerate(food_df['food_id'])}

# Add nutrient and disease nodes
data['nutrient'].x = torch.eye(len(nutrition_df))
data['disease'].x = torch.eye(len(disease_df))

# Add edges
edge_index_dict = defaultdict(list)
for _, row in edges.iterrows():
    src, rel, tgt = row['source'], row['relation'], row['target']
    
    if rel == "hasRisk" and src in user_id_map:
        edge_index_dict[('user', 'hasRisk', 'disease')].append([user_id_map[src], 0])
    
    elif rel == "contains" and src in food_id_map:
        edge_index_dict[('food', 'contains', 'nutrient')].append([food_id_map[src], int(tgt[1:]) - 1])

# Convert edges to tensors
for edge_type, edge_list in edge_index_dict.items():
    edge_tensor = torch.tensor(edge_list, dtype=torch.long).t().contiguous()
    data[edge_type].edge_index = edge_tensor

In [12]:

from torch.nn import Linear
from torch_geometric.nn import GATConv, HeteroConv
import torch.nn.functional as F

class GNN(torch.nn.Module):
    def __init__(self, hidden_channels):
        super().__init__()
        self.conv1 = HeteroConv({
    ('user', 'hasRisk', 'disease'): GATConv((-1, -1), hidden_channels, add_self_loops=False),
    ('food', 'contains', 'nutrient'): GATConv((-1, -1), hidden_channels, add_self_loops=False),
    ('disease', 'rev_hasRisk', 'user'): GATConv((-1, -1), hidden_channels, add_self_loops=False),
    ('nutrient', 'rev_contains', 'food'): GATConv((-1, -1), hidden_channels, add_self_loops=False),
}, aggr='sum')


        self.lin = Linear(hidden_channels, hidden_channels)

    def forward(self, x_dict, edge_index_dict):
        x_dict = self.conv1(x_dict, edge_index_dict)
        x_dict = {k: F.relu(v) for k, v in x_dict.items()}
        x_dict = {k: self.lin(v) for k, v in x_dict.items()}
        return x_dict

In [13]:
# Add reverse edges for message passing INTO 'user' and 'food'
if ('user', 'hasRisk', 'disease') in data.edge_index_dict:
    edge = data['user', 'hasRisk', 'disease'].edge_index
    data['disease', 'rev_hasRisk', 'user'].edge_index = edge.flip(0)

if ('food', 'contains', 'nutrient') in data.edge_index_dict:
    edge = data['food', 'contains', 'nutrient'].edge_index
    data['nutrient', 'rev_contains', 'food'].edge_index = edge.flip(0)

In [14]:
model = GNN(hidden_channels=64)  # or another number depending on your setup
model.eval()

with torch.no_grad():
    out = model(data.x_dict, data.edge_index_dict)
user_emb = out['user']   # [num_users, hidden_dim]
food_emb = out['food']   # [num_foods, hidden_dim]

In [15]:
# Dot product similarity between each user and each food
scores = torch.matmul(user_emb, food_emb.T)  # Shape: [num_users, num_foods]

In [16]:
top_k = 5  # Number of foods to recommend per user
top_scores, top_indices = torch.topk(scores, k=top_k, dim=1)

In [17]:
# If you used this earlier:
# food_id_map = {food_id_string: index}
index_to_food_id = {idx: fid for fid, idx in food_id_map.items()}

# Example: recommendations for first user
print("Top recommendations for User 0:")
for food_idx in top_indices[0]:
    print(index_to_food_id[int(food_idx)])

Top recommendations for User 0:
f1003
f1004
f1001
f1000
f1002

In [18]:
print(data)

HeteroData(
  user={ x=[1062, 14] },
  food={ x=[2500, 6] },
  nutrient={ x=[4, 4] },
  disease={ x=[1, 1] },
  (user, hasRisk, disease)={ edge_index=[2, 1062] },
  (food, contains, nutrient)={ edge_index=[2, 4503] },
  (disease, rev_hasRisk, user)={ edge_index=[2, 1062] },
  (nutrient, rev_contains, food)={ edge_index=[2, 4503] }
)

In [19]:
print(data['user', 'hasRisk', 'disease'].edge_index.shape)
print(data['food', 'contains', 'nutrient'].edge_index.shape)

torch.Size([2, 1062])
torch.Size([2, 4503])

In [20]:
print(data['user', 'hasRisk', 'disease'].edge_index.T[:5])  # First 5 edges

tensor([[0, 0],
        [1, 0],
        [2, 0],
        [3, 0],
        [4, 0]])

In [35]:
import pandas as pd
import random
import json

# 🧑‍⚕️ User Profile with Risk Factors
test_user = {
    "user_id": "u101",
    "Age": 45,
    "Gender": "Female",
    "BMI": 28.0,                # High BMI (Overweight)
    "DiabetesRisk": 0.8,        # High Diabetes Risk
    "Preferences": "Sri Lankan"
}

# 🍱 Categories
categories = ["Breakfast", "Lunch", "Dinner", "Snack"]

# ✅ Suitability with Risk Reduction
def is_suitable_risk_aware(food, user):
    # Diabetic filtering
    if user["DiabetesRisk"] > 0.6:
        if food["glycemic_index"] > 55 or food["carbs"] > 60:
            return False
    
    # Obesity filtering
    if user["BMI"] > 25:
        if food["calories"] > 700 or food["fat"] > 25:
            return False

    # Overeating portion filtering
    if food["estimated_weight_g"] > 800:
        return False

    # Cultural match
    if food["culture"] != user["Preferences"]:
        return False

    return True

# 🧠 Plan Generator
def generate_health_aware_meal_plan(user, food_df):
    used_food_ids = set()
    meal_plan = {}

    for day in range(1, 8):
        daily_plan = {}
        for meal in categories:
            options = food_df[
                (food_df["meal_type"] == meal) &
                (~food_df["food_id"].isin(used_food_ids))
            ].copy()

            options = options[options.apply(lambda row: is_suitable_risk_aware(row, user), axis=1)]

            if options.empty:
                daily_plan[meal] = {
                    "food": "No suitable meal",
                    "estimated_weight_g": 0,
                    "calories": 0,
                    "carbs": 0,
                    "protein": 0,
                    "fat": 0,
                    "glycemic_index": "-"
                }
            else:
                chosen = options.sample(1).iloc[0]
                used_food_ids.add(str(chosen["food_id"]))
                daily_plan[meal] = {
                    "food": str(chosen["food_item"]),
                    "estimated_weight_g": int(chosen["estimated_weight_g"]),
                    "calories": float(chosen["calories"]),
                    "carbs": float(chosen["carbs"]),
                    "protein": float(chosen["protein"]),
                    "fat": float(chosen["fat"]),
                    "glycemic_index": int(chosen["glycemic_index"])
                }

        meal_plan[f"Day {day}"] = daily_plan

    return meal_plan

# 🛠️ Run the plan generator
meal_plan = generate_health_aware_meal_plan(test_user, food_df)

# 📤 Output
print(json.dumps(meal_plan, indent=2))

{
  "Day 1": {
    "Breakfast": {
      "food": "Kurakkan with beef and cabbage",
      "estimated_weight_g": 258,
      "calories": 335.8030593,
      "carbs": 5.8,
      "protein": 54.6,
      "fat": 9.3,
      "glycemic_index": 52
    },
    "Lunch": {
      "food": "Bread with tofu and cabbage",
      "estimated_weight_g": 368,
      "calories": 478.0114723,
      "carbs": 53.5,
      "protein": 22.4,
      "fat": 15.7,
      "glycemic_index": 46
    },
    "Dinner": {
      "food": "Bread with tofu and cucumber",
      "estimated_weight_g": 403,
      "calories": 523.9005736,
      "carbs": 32.5,
      "protein": 43.1,
      "fat": 22.2,
      "glycemic_index": 54
    },
    "Snack": {
      "food": "Kurakkan with mung beans and carrot",
      "estimated_weight_g": 269,
      "calories": 350.1434034,
      "carbs": 12.1,
      "protein": 27.6,
      "fat": 20.2,
      "glycemic_index": 54
    }
  },
  "Day 2": {
    "Breakfast": {
      "food": "Kurakkan with lentils and beans",
      "estimated_weight_g": 449,
      "calories": 583.6520076,
      "carbs": 48.2,
      "protein": 46.2,
      "fat": 21.7,
      "glycemic_index": 50
    },
    "Lunch": {
      "food": "Kurakkan with egg and tomato",
      "estimated_weight_g": 392,
      "calories": 510.0382409,
      "carbs": 47.7,
      "protein": 30.4,
      "fat": 19.7,
      "glycemic_index": 52
    },
    "Dinner": {
      "food": "Rice with mung beans and cucumber",
      "estimated_weight_g": 373,
      "calories": 484.4646272,
      "carbs": 56.3,
      "protein": 23.6,
      "fat": 16.5,
      "glycemic_index": 48
    },
    "Snack": {
      "food": "Kurakkan with tofu and beans",
      "estimated_weight_g": 326,
      "calories": 424.2351816,
      "carbs": 22.4,
      "protein": 49.8,
      "fat": 11.6,
      "glycemic_index": 55
    }
  },
  "Day 3": {
    "Breakfast": {
      "food": "Millet with lentils and cabbage",
      "estimated_weight_g": 418,
      "calories": 543.7380497,
      "carbs": 53.3,
      "protein": 26.0,
      "fat": 22.0,
      "glycemic_index": 53
    },
    "Lunch": {
      "food": "Kurakkan with lentils and cabbage",
      "estimated_weight_g": 318,
      "calories": 413.4799235,
      "carbs": 33.6,
      "protein": 28.3,
      "fat": 16.2,
      "glycemic_index": 46
    },
    "Dinner": {
      "food": "Millet with chicken and beans",
      "estimated_weight_g": 394,
      "calories": 511.7112811,
      "carbs": 38.3,
      "protein": 50.3,
      "fat": 16.7,
      "glycemic_index": 46
    },
    "Snack": {
      "food": "Bread with mung beans and beans",
      "estimated_weight_g": 348,
      "calories": 451.959847,
      "carbs": 31.7,
      "protein": 30.6,
      "fat": 20.8,
      "glycemic_index": 45
    }
  },
  "Day 4": {
    "Breakfast": {
      "food": "Bread with fish and cabbage",
      "estimated_weight_g": 365,
      "calories": 474.1873805,
      "carbs": 42.2,
      "protein": 31.8,
      "fat": 18.5,
      "glycemic_index": 47
    },
    "Lunch": {
      "food": "Wheat with fish and cabbage",
      "estimated_weight_g": 524,
      "calories": 681.6443595,
      "carbs": 41.3,
      "protein": 68.6,
      "fat": 24.8,
      "glycemic_index": 52
    },
    "Dinner": {
      "food": "Rice with beef and beans",
      "estimated_weight_g": 339,
      "calories": 440.9655832,
      "carbs": 59.7,
      "protein": 13.8,
      "fat": 15.0,
      "glycemic_index": 55
    },
    "Snack": {
      "food": "Kurakkan with egg and cucumber",
      "estimated_weight_g": 486,
      "calories": 631.9311663,
      "carbs": 59.3,
      "protein": 41.5,
      "fat": 23.5,
      "glycemic_index": 49
    }
  },
  "Day 5": {
    "Breakfast": {
      "food": "Bread with lentils and beans",
      "estimated_weight_g": 464,
      "calories": 603.0114723,
      "carbs": 58.0,
      "protein": 36.4,
      "fat": 23.4,
      "glycemic_index": 54
    },
    "Lunch": {
      "food": "Bread with mung beans and beans",
      "estimated_weight_g": 514,
      "calories": 668.499044,
      "carbs": 59.1,
      "protein": 47.9,
      "fat": 21.9,
      "glycemic_index": 53
    },
    "Dinner": {
      "food": "Kurakkan with mung beans and cabbage",
      "estimated_weight_g": 199,
      "calories": 259.082218,
      "carbs": 47.1,
      "protein": 5.5,
      "fat": 4.0,
      "glycemic_index": 52
    },
    "Snack": {
      "food": "Kurakkan with tofu and cucumber",
      "estimated_weight_g": 386,
      "calories": 501.4340344,
      "carbs": 15.7,
      "protein": 57.3,
      "fat": 22.0,
      "glycemic_index": 51
    }
  },
  "Day 6": {
    "Breakfast": {
      "food": "Kurakkan with tofu and beans",
      "estimated_weight_g": 457,
      "calories": 594.6462715,
      "carbs": 51.3,
      "protein": 47.1,
      "fat": 21.2,
      "glycemic_index": 49
    },
    "Lunch": {
      "food": "Kurakkan with lentils and tomato",
      "estimated_weight_g": 355,
      "calories": 461.7590822,
      "carbs": 54.2,
      "protein": 21.5,
      "fat": 14.6,
      "glycemic_index": 51
    },
    "Dinner": {
      "food": "Kurakkan with tofu and beans",
      "estimated_weight_g": 223,
      "calories": 289.6749522,
      "carbs": 38.6,
      "protein": 14.1,
      "fat": 8.1,
      "glycemic_index": 47
    },
    "Snack": {
      "food": "Kurakkan with mung beans and cabbage",
      "estimated_weight_g": 372,
      "calories": 483.9866157,
      "carbs": 48.5,
      "protein": 16.7,
      "fat": 23.3,
      "glycemic_index": 46
    }
  },
  "Day 7": {
    "Breakfast": {
      "food": "Millet with mung beans and cabbage",
      "estimated_weight_g": 292,
      "calories": 379.7801147,
      "carbs": 34.5,
      "protein": 20.0,
      "fat": 17.0,
      "glycemic_index": 47
    },
    "Lunch": {
      "food": "Bread with lentils and cucumber",
      "estimated_weight_g": 536,
      "calories": 696.9407266,
      "carbs": 57.3,
      "protein": 68.2,
      "fat": 19.3,
      "glycemic_index": 48
    },
    "Dinner": {
      "food": "Millet with tofu and tomato",
      "estimated_weight_g": 507,
      "calories": 659.416826,
      "carbs": 57.6,
      "protein": 56.1,
      "fat": 21.1,
      "glycemic_index": 51
    },
    "Snack": {
      "food": "Rice with fish and onion",
      "estimated_weight_g": 484,
      "calories": 629.3021033,
      "carbs": 25.7,
      "protein": 77.0,
      "fat": 22.6,
      "glycemic_index": 49
    }
  }
}