In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

### Load Datasets

In [2]:
exercise_df = pd.read_csv('../../data/RecommandationDatasets/exercises.csv')

In [3]:
exercise_df.head()

,name,force,level,mechanic,equipment,primaryMuscles__-,secondaryMuscles__001,secondaryMuscles__002,secondaryMuscles__003,instructions__-,...,secondaryMuscles__006,secondaryMuscles__007,secondaryMuscles__008,secondaryMuscles__009,secondaryMuscles__010,instructions,category,images__001,images__002,id
0,3/4 Sit-Up,pull,beginner,compound,body only,abdominals,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Lie down on the floor and secure your feet. Yo...,strength,3_4_Sit-Up/0.jpg,3_4_Sit-Up/1.jpg,3_4_Sit-Up
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Place your hands behind or to the side of your...,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Flex your hips and spine to raise your torso t...,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,At the top of the contraction your torso shoul...,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Repeat for the recommended amount of repetitions.,NaN,NaN,NaN,NaN

In [4]:
exercise_df.shape

(3725, 22)

In [5]:
exercise_df = exercise_df.drop(columns=['images__001', 'images__002', 'id','instructions__-'])

In [6]:
exercise_df = exercise_df.dropna(subset=['name'])

exercise_df.info()

In [7]:
exercise_df.isna().sum()

name                       0
force                     29
level                      0
mechanic                  87
equipment                 77
primaryMuscles__-          0
secondaryMuscles__001    272
secondaryMuscles__002    412
secondaryMuscles__003    592
secondaryMuscles__004    725
secondaryMuscles__005    771
secondaryMuscles__006    817
secondaryMuscles__007    839
secondaryMuscles__008    858
secondaryMuscles__009    865
secondaryMuscles__010    869
instructions              15
category                   0
dtype: int64

In [8]:
exercise_df.duplicated().sum()

0

In [9]:
exercise_df.head()

,name,force,level,mechanic,equipment,primaryMuscles__-,secondaryMuscles__001,secondaryMuscles__002,secondaryMuscles__003,secondaryMuscles__004,secondaryMuscles__005,secondaryMuscles__006,secondaryMuscles__007,secondaryMuscles__008,secondaryMuscles__009,secondaryMuscles__010,instructions,category
0,3/4 Sit-Up,pull,beginner,compound,body only,abdominals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lie down on the floor and secure your feet. Yo...,strength
5,90/90 Hamstring,push,beginner,NaN,body only,hamstrings,calves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Lie on your back, with one leg extended straig...",stretching
9,Ab Crunch Machine,pull,intermediate,isolation,machine,abdominals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Select a light resistance and sit down on the ...,strength
13,Ab Roller,pull,intermediate,compound,other,abdominals,shoulders,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hold the Ab Roller with both hands and kneel o...,strength
17,Adductor,static,intermediate,isolation,foam roll,adductors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lie face down with one leg on a foam roll.,stretching

In [10]:
exercise_df = exercise_df.fillna("None")

In [11]:
exercise_df.head()

,name,force,level,mechanic,equipment,primaryMuscles__-,secondaryMuscles__001,secondaryMuscles__002,secondaryMuscles__003,secondaryMuscles__004,secondaryMuscles__005,secondaryMuscles__006,secondaryMuscles__007,secondaryMuscles__008,secondaryMuscles__009,secondaryMuscles__010,instructions,category
0,3/4 Sit-Up,pull,beginner,compound,body only,abdominals,None,None,None,None,None,None,None,None,None,None,Lie down on the floor and secure your feet. Yo...,strength
5,90/90 Hamstring,push,beginner,None,body only,hamstrings,calves,None,None,None,None,None,None,None,None,None,"Lie on your back, with one leg extended straig...",stretching
9,Ab Crunch Machine,pull,intermediate,isolation,machine,abdominals,None,None,None,None,None,None,None,None,None,None,Select a light resistance and sit down on the ...,strength
13,Ab Roller,pull,intermediate,compound,other,abdominals,shoulders,None,None,None,None,None,None,None,None,None,Hold the Ab Roller with both hands and kneel o...,strength
17,Adductor,static,intermediate,isolation,foam roll,adductors,None,None,None,None,None,None,None,None,None,None,Lie face down with one leg on a foam roll.,stretching

In [12]:
exercise_df.isna().sum()

name                     0
force                    0
level                    0
mechanic                 0
equipment                0
primaryMuscles__-        0
secondaryMuscles__001    0
secondaryMuscles__002    0
secondaryMuscles__003    0
secondaryMuscles__004    0
secondaryMuscles__005    0
secondaryMuscles__006    0
secondaryMuscles__007    0
secondaryMuscles__008    0
secondaryMuscles__009    0
secondaryMuscles__010    0
instructions             0
category                 0
dtype: int64

In [13]:
exercise_df.to_csv("../../data/RecommandationDatasets/GymDatasets/GymExercises.csv", index=False)

In [14]:
exercise_df.shape

(873, 18)